version: '3'

services:

    mom_mock:
        container_name: mom_mock
        restart: always
        build:
            context: ./docker/php
        ports:
            - 9001:9001
        volumes:
            - ./magento24/mom-mock:/var/www/magento24/mom-mock:cached
            - ./docker/php/mom-mock-www.conf:/usr/local/etc/php-fpm.d/mom-mock-www.conf

    php:
        container_name: php_24
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./magento24:/var/www/magento24:cached
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=magento24"
        links:
            - redis
 
    nginx:
        container_name: nginx_24
        image: nginx:1.14-alpine
        ports:
            - 80:80
        volumes:
            - ./magento24:/var/www/magento24:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mom_mock
 
    db:
        container_name: mariadb_24
        image: mariadb:10.4
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    mailhog:
        container_name: mail_24
        image: mailhog/mailhog:latest
        links:
            - php
        ports:
            - "1025:1025"
            - "8025:8025"
            
    redis:
        container_name: redis_24
        image: redis:latest

    rabbitmq:
        container_name: rabbitmq_24
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"

    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch_24
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            "discovery.type": "single-node"

volumes:
    magento24: